name: Build Android apk

on:
  workflow_dispatch:
    inputs:
      comments:
        description: 'Comments'
        required: true
        default: 'Manual build Actions'

  push:
    branches:
      - feature/continous-integeration

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: '{{ secrets.CLIENT_ID }}'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Installing Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli
      - name: Install yarn dependencies
        run: |
          yarn install
      
      - name: Create config file
        run: |
          cp ./config/config.sample.js ./config/config.js

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<client-id>"
          replace: "$CLIENT_ID"
          include: "./config/config.js"
      - name: Echo client id
        run: |
          echo $CLIENT_ID
      # - name: Test printing your secret (Remove this step in production)
      #   run: cat $HOME/secrets/CLIENT_GITHUB_ID.json

      # - name: Make Gradlew Executable
      #   run: cd android && chmod +x ./gradlew
      # - name: Build Android Release
      #   run: |
      #     cd android && ./gradlew assembleRelease --no-daemon
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release.apk
      #     path: android/app/build/outputs/apk/release/
      # - name: Download a single artifact    
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: app-release.apk