name: Continous-Integeration
on:
  pull_request:
    branches:
      - test-develop

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Installing node
        uses: actions/setup-node@v1
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli
      - name: Install node modules
        run: |
          yarn install
      - name: Running test
        run: |
          yarn test